{
 "title": "Logs",
 "tags": [
  "order-service",
  "product-service",
  "loki"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Order Service Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"flask\", filename=~\".*order.*\"}"
    }
   ]
  },
  {
   "title": "Product Service Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"flask\", filename=~\".*product.*\"}"
    }
   ]
  },
  {
   "title": "All Logs (combined)",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "{job=\"flask\"}"
    }
   ]
  }
 ]
}